/**
 * Shape of `public/constellations.json`, generated by
 * `scripts/build-constellations.ts`.
 */
export interface ConstellationLines {
  source: string;
  sourceUrl: string;
  segmentCount: number;
  /** Right ascension in hours, J2000; two entries per segment */
  ra: number[];
  /** Declination in degrees, J2000; two entries per segment */
  dec: number[];
  /** One entry per constellation, placed at the centre of its figure */
  labels: {
    name: string;
    ra: number;
    dec: number;
    /** 1 for the most prominent constellations, 3 for the faintest */
    rank: number;
  }[];
}
