/**
 * Shape of `public/stars.json`, generated by `scripts/build-stars.ts`.
 *
 * The arrays are parallel and sorted by increasing magnitude, so index `i`
 * describes the same star in every one of them.
 */
export interface StarCatalogue {
  source: string;
  sourceUrl: string;
  magnitudeLimit: number;
  count: number;
  /** Right ascension in hours, J2000 */
  ra: number[];
  /** Declination in degrees, J2000 */
  dec: number[];
  /** Apparent visual magnitude */
  mag: number[];
  /** B−V colour index */
  ci: number[];
  /** Proper names, by index into the arrays above */
  names: { i: number; name: string }[];
}

/**
 * Effective temperature in kelvin for a B−V colour index, using Ballesteros'
 * formula. Good enough across the range main-sequence stars actually cover.
 */
export function colourIndexToKelvin(colourIndex: number): number {
  const bv = Math.min(Math.max(colourIndex, -0.4), 2.5);
  return 4600 * (1 / (0.92 * bv + 1.7) + 1 / (0.92 * bv + 0.62));
}

/**
 * Approximate sRGB colour of a blackbody at the given temperature, each
 * channel in 0..1. Adapted from Tanner Helland's widely used fit.
 */
export function kelvinToRgb(kelvin: number): [number, number, number] {
  const t = Math.min(Math.max(kelvin, 1000), 40000) / 100;
  const clamp = (value: number) => Math.min(Math.max(value, 0), 255) / 255;

  const red = t <= 66 ? 255 : 329.698727446 * (t - 60) ** -0.1332047592;

  const green =
    t <= 66
      ? 99.4708025861 * Math.log(t) - 161.1195681661
      : 288.1221695283 * (t - 60) ** -0.0755148492;

  const blue =
    t >= 66
      ? 255
      : t <= 19
        ? 0
        : 138.5177312231 * Math.log(t - 10) - 305.0447927307;

  return [clamp(red), clamp(green), clamp(blue)];
}
